# Generated by Django 3.2.5 on 2021-11-29 18:37

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADMINS',
            fields=[
                ('adminID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('adminName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('numSeats', models.IntegerField()),
                ('numAvail', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CUSTOMERS',
            fields=[
                ('custID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('custName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FLIGHTS',
            fields=[
                ('flightNum', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('price', models.IntegerField()),
                ('numSeats', models.IntegerField()),
                ('numAvial', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LOCATIONS',
            fields=[
                ('location', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('riskLevel', models.CharField(choices=[('低', '低'), ('中', '中'), ('高', '高')], default='低', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HOTELS',
            fields=[
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TravelBooking.locations')),
                ('price', models.IntegerField()),
                ('numRooms', models.IntegerField()),
                ('numAvail', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RES_HOTEL',
            fields=[
                ('resvKey', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('custID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelBooking.customers')),
                ('hotelLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelBooking.locations')),
            ],
        ),
        migrations.CreateModel(
            name='RES_FLIGHT',
            fields=[
                ('resvKey', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('custID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelBooking.customers')),
                ('flightNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelBooking.flights')),
            ],
        ),
        migrations.CreateModel(
            name='RES_BUS',
            fields=[
                ('resvKey', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('busLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelBooking.locations')),
                ('custID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelBooking.customers')),
            ],
        ),
        migrations.AddField(
            model_name='flights',
            name='ArivCity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArivCity', to='TravelBooking.locations'),
        ),
        migrations.AddField(
            model_name='flights',
            name='FromCity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FromCity', to='TravelBooking.locations'),
        ),
        migrations.AddConstraint(
            model_name='customers',
            constraint=models.CheckConstraint(check=models.Q(('balance', django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('balance'), '-', django.db.models.expressions.Value(0)))), name='check_balance'),
        ),
        migrations.AddField(
            model_name='bus',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelBooking.locations'),
        ),
        migrations.AddConstraint(
            model_name='hotels',
            constraint=models.CheckConstraint(check=models.Q(('price', django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('price'), '-', django.db.models.expressions.Value(0)))), name='check_h_price'),
        ),
        migrations.AddConstraint(
            model_name='flights',
            constraint=models.CheckConstraint(check=models.Q(('price', django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('price'), '-', django.db.models.expressions.Value(0)))), name='check_f_price'),
        ),
        migrations.AddConstraint(
            model_name='bus',
            constraint=models.CheckConstraint(check=models.Q(('price', django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('price'), '-', django.db.models.expressions.Value(0)))), name='check_b_price'),
        ),
    ]
