# Generated by Django 3.2.5 on 2021-11-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='riskLevel',
            field=models.CharField(choices=[('中', '中'), ('低', '低'), ('高', '高')], default='低', max_length=50),
        ),
    ]
