# Generated by Django 3.2.5 on 2021-11-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBooking', '0003_alter_locations_risklevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='riskLevel',
            field=models.CharField(choices=[('低', '低'), ('中', '中'), ('高', '高')], default='低', max_length=50),
        ),
    ]
