# Generated by Django 3.2.5 on 2021-11-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBooking', '0004_alter_locations_risklevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='id',
        ),
        migrations.AlterField(
            model_name='bus',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TravelBooking.locations'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='riskLevel',
            field=models.CharField(choices=[('高', '高'), ('低', '低'), ('中', '中')], default='低', max_length=50),
        ),
    ]
