# Generated by Django 3.2.5 on 2021-11-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBooking', '0005_auto_20211129_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flights',
            old_name='numAvial',
            new_name='numAvail',
        ),
        migrations.AlterField(
            model_name='locations',
            name='riskLevel',
            field=models.CharField(choices=[('低', '低'), ('中', '中'), ('高', '高')], default='低', max_length=50),
        ),
    ]
