# Generated by Django 3.2.5 on 2021-11-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBooking', '0006_auto_20211129_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='res_flight',
            name='buildTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='res_flight',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='res_flight',
            name='resStatus',
            field=models.CharField(choices=[('正在预约', '正在预约'), ('已预约', '已预约'), ('订单已开始', '订单已开始'), ('订单已完成', '订单已完成')], default='正在预约', max_length=50),
        ),
        migrations.AddField(
            model_name='res_flight',
            name='startTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='riskLevel',
            field=models.CharField(choices=[('高', '高'), ('中', '中'), ('低', '低')], default='低', max_length=50),
        ),
        migrations.AlterField(
            model_name='res_bus',
            name='resvKey',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='res_flight',
            name='resvKey',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='res_hotel',
            name='resvKey',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
