# Generated by Django 3.2.5 on 2021-11-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBooking', '0007_auto_20211130_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='res_bus',
            name='buildTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='res_bus',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='res_bus',
            name='resStatus',
            field=models.CharField(choices=[('正在预约', '正在预约'), ('已预约', '已预约'), ('订单已开始', '订单已开始'), ('订单已完成', '订单已完成')], default='正在预约', max_length=50),
        ),
        migrations.AddField(
            model_name='res_bus',
            name='startTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='res_hotel',
            name='buildTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='res_hotel',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='res_hotel',
            name='resStatus',
            field=models.CharField(choices=[('正在预约', '正在预约'), ('已预约', '已预约'), ('订单已开始', '订单已开始'), ('订单已完成', '订单已完成')], default='正在预约', max_length=50),
        ),
        migrations.AddField(
            model_name='res_hotel',
            name='startTime',
            field=models.DateTimeField(null=True),
        ),
    ]
